spring:
  mvc:
    locale-resolver: fixed
    locale: pt_BR
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/park_car?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update