spring:
  mvc:
    locale-resolver: fixed
    locale: pt_BR
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/park_car?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /docs-park.html
  api-docs:
    path: /docs-park
  packagesToScan: com.poc.parkapi.web.controller

JWT_SECRET_KEY: gdfDH46d4FHG3gH$#GH6GFf65g4dy4t6hgf65h4